apiVersion: v1
kind: Namespace
metadata:
  name: mentat
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mentat
  namespace: mentat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-nodes
subjects:
- kind: ServiceAccount
  name: mentat
  namespace: mentat
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
---
kind: Service
apiVersion: v1
metadata:
  name: mentat
  namespace: mentat
spec:
  selector:
    app: mentat
  ports:
  - protocol: TCP
    port: 2112
    targetPort: 2112
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mentat
  namespace: mentat
  labels:
    app: mentat
spec:
  selector:
    matchLabels:
      app: mentat
  template:
    metadata:
      labels:
        app: mentat
    spec:
      serviceAccountName: mentat
      containers:
      - name: mentat
        image: ghcr.io/amarchese96/mentat:latest
        ports:
        - containerPort: 2112
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SLEEP_SECONDS
          value: "5"
